[package]
name = "world_ui"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
common = { workspace = true }
scene_material = { workspace = true }

bevy = { workspace = true }
boimp = { workspace = true }
