[package]
name = "input_manager"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
dcl_component = { workspace = true }

bevy = { workspace = true }
bevy_console = { workspace = true }
bevy_egui = { workspace = true }
bimap = { workspace = true }
